"""cria tabelas de inscricoes e acompanhantes

Revision ID: 85cc278ad888
Revises: 
Create Date: 2026-07-14 11:43:56.661261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cc278ad888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.Enum('participante', 'palestrante', 'vip', 'imprensa', name='categoria_inscricao'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmada', 'lista_de_espera', 'check_in_feito', name='status_inscricao'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acompanhantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscricao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('restricao_alimentar', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['inscricao_id'], ['inscricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acompanhantes')
    op.drop_table('inscricoes')
    # ### end Alembic commands ###
